#!/usr/bin/env python

# CAVEAT UTILITOR
#
# This file was automatically generated by TatSu.
#
#    https://pypi.python.org/pypi/tatsu/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.

from __future__ import annotations

from typing import Any
from dataclasses import dataclass

from tatsu.objectmodel import Node
from tatsu.semantics import ModelBuilderSemantics


@dataclass(eq=False)
class ModelBase(Node):
    pass


class ZahlenModelBuilderSemantics(ModelBuilderSemantics):
    def __init__(self, context=None, types=None):
        types = [
            t for t in globals().values()
            if type(t) is type and issubclass(t, ModelBase)
        ] + (types or [])
        super().__init__(context=context, types=types)


@dataclass(eq=False)
class Program(ModelBase):
    statements: Any = None


@dataclass(eq=False)
class LabledStatement(ModelBase):
    label: Any = None
    stmt: Any = None


@dataclass(eq=False)
class Assignment(ModelBase):
    expr: Any = None
    varname: Any = None


@dataclass(eq=False)
class IfElse(ModelBase):
    false_stmt: Any = None
    pred: Any = None
    true_stmt: Any = None


@dataclass(eq=False)
class GoTo(ModelBase):
    label: Any = None


@dataclass(eq=False)
class Print(ModelBase):
    varname: Any = None
